spring:
  application:
    name: application
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: create-drop
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.erikwiberg.se:3306/car_repair_shop 
    username: jonahe 
    password: jonahe
  data:
    cassandra:
      connect-timeout-millis: 3000
  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  context-path: /filmr
  
loggin:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    filmr: INFO