  spring:
    application:
      name: application
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: create-drop
    datasource:
      driverClassName: com.mysql.jdbc.Driver
    data:
      cassandra:
        connect-timeout-millis: 3000
    jackson:
      serialization:
        fail-on-empty-beans: false
        write-dates-as-timestamps: false

  server:
    context-path: /filmr

  logging:
    file: filmr_log.txt
    level:
      org.springframework.web: DEBUG
      org.hibernate: ERROR
      filmr: DEBUG